### ISSUE TITLE
Does not Initialize

### ISSUE THREAD

**Issue by SpectralEdge** [github-for-unity/Unity#1011]
I seem to be having this exact problem (https://github.com/github-for-unity/Unity/issues/650) still. But it looks like it was fixed last year. So I'm not sure why I am having it. 

[github-unity.log](https://github.com/github-for-unity/Unity/files/2819222/github-unity.log)

### Steps to Reproduce

1. Create new project.
2. Download latest github for unity
3. Try to initialize

**Expected behavior:** Initialization

**Actual behavior:** Clicking the button a bar shows up and fills about 20% then closes. Nothing else happens.

**Reproduces how often:** Every time

### Additional Information

I am on windows.

**Comment by Deathevn** [comment]
I've got the same problem. My unity-version is 2019.1.0a13 and am tested ist with github for unity version 1.2.0 and 1.2.1.6394. Same behaviour as described by SpectralEdge. 
[github-unity.log](https://github.com/github-for-unity/Unity/files/2836175/github-unity.log)

**Comment by StanleyGoldman** [comment]
Hey @SpectralEdge and @Deathevn sorry I haven't gotten back to you sooner. 🤹‍♂️ I'm juggling a few different projects at the same time.

Yes this bug is odd.
So i'm going to take a blind guess and we are going to force a reinstall of the git internals.

Perform these steps while Unity is not running.
1. Delete if exists `C:\ProgramData\GitHubUnity\systemsettings.json`
2. Delete if exists `%USERPROFILE%\AppData\Local\GitHubUnity\git`
3. Delete if exists `%USERPROFILE%\AppData\Local\GitHubUnity\git-lfs`
4. Restart the project with GitHub for Unity.

I'm just gonna pray that this fixes your issue. 🙏 📿

**Comment by Deathevn** [comment]
Hi @StanleyGoldman I tried this several times without success and my solution was to install git and git-lfs via the official windows installer and set the paths inside github-for-unity accordingly.

**Comment by StanleyGoldman** [comment]
@Deathevn are you still able to reproduce the issue if you change the exec paths of github for unity?

**Comment by Deathevn** [comment]
@StanleyGoldman I changed the paths inside the GithubForUnity-window back to the original ones (C:\Users\username\AppDataLocal\GitHubUnity\...) and right now everything is working. Git and Git-LFS are still installed from their own windows-installer.

**Comment by StanleyGoldman** [comment]
So since everything is all good for everyone here. I'm going to close out this issue.
Feel free to re-open it if you need.
