### ISSUE TITLE
[Help]  How do I use my project on another computer?

### ISSUE THREAD

**Issue by BudsofBuds** [github-for-unity/Unity#1077]
I want to use source control to use my project on different computers (mac and pc).  The startup documentation doesn't tell me how to properly set up the project on the second computer.

When I set up git for unity it has me create a new project (with it's own initial commit) which makes it so that it doesn't share a history with the version on GitHub which makes pull impossible

What do I need to do to be able to pull the project on another computer?

**Comment by matthewbegun** [comment]
I use the github desktop client to clone the repository from GitHub.

then when I open it on unity for the first time it works.

All on windows 10.

**Comment by vestigialdev** [comment]
I'm new to git but I came up with the same solution as the previous answer. 
To elaborate a little, once you use install and use GitHub Desktop to pull the repository into the folder you want to use, you can then open Unity Hub and tell it to Add an existing project. Point it to the folder you just pulled to, and it'll get confused since theres no project files there, and you'll go through the "Opening Project in Non-Matching Editor Installation" wizard, "The saved project (before 5.0) does not match the launched editor..." etc. Once you click through that, it'll go through the version upgrade process (actually more like setting up the project for the first time). Once thats complete there should be "Rebuilding Library because the asset database cannot be found!" in the console and you should be able to open up the package manager and import GitHub for Unity. 

Then you can open Window/Github and paste in the repository address into Repository Configuration under the settings tab. At that point the "changes" window should be empty so you can pull without having to push first. Its messy but it seems to work.
