### ISSUE TITLE
What's the development status of Github for Unity? Is it abandoned?

### ISSUE THREAD

**Issue by OscarAbraham** [github-for-unity/Unity#1107]
Hello, this seems like an awesome project with some very nice goals. I think that all the developers that have worked on it are probably awesome. It seems like it has been some time since it's been kind of broken, though. There are a lot vital issues that seem to keep piling on. Also, it seems that its been some time since its been developed. Has it become abandonware? Are there people still maintaining it? Should it be archived?

This project is the first thing that search engines give when feeding them "Github Unity".  I imagine that I've not been the only one that has ended up at least a little frustrated after trying to make this work. If there was a proper notice of the actual current status of this project, I think it could save time and energy for lots of people.

I want to say that I mean no disrespect to anyone. If anything, I really admire all the time and effort developers have put into this. I understand that sometimes a person has a lot more important things than to pay attention to a FOSS project. I just think it could be very helpful for other people if this project got out of the limbo, one way or the other.

**Comment by shana** [comment]
Hi. Yeah, this project has no internal teams assigned to it and exists as-is. Unity has forked it to https://github.com/Unity-Technologies/Git-for-Unity, and that one is the same codebase and almost same features in a package format, minus the Github-specific functionalities like login and publish (because it's Git for Unity). It's on my todo list to update this project to match the updates I did on Git for Unity (which should get rid of a bunch of bugs), but, well, 2020 comes at you fast these days and it's my personal time on this, so....

Now that easily updateable source packages are a thing in Unity, you might find it more useful to grab Git for Unity and customize it to your needs.

**Comment by OscarAbraham** [comment]
Thank you very much Shana. That's what I'll do. I'll close this issue then if that's ok.
