### ISSUE TITLE
Can't push!

### ISSUE THREAD

**Issue by gilbertobitt** [github-for-unity/Unity#114]
### Description

I config a project and i setup everything when i push appears that can't push!

i have a private repository!

here is the log!
[github-unity.zip](https://github.com/github-for-unity/Unity/files/1138772/github-unity.zip)

**Comment by StanleyGoldman** [comment]
Hey @gilbertobitt. Thanks for testing our stuff out. 🥇  

We support pushing and pulling with an HTTPS based remote, not SSH.
Also, in the Authentication window, you are supposed to use your username not your email.

_(I have to test what happens when I use my email. I may have to add a warning if I see a user try to use their email.)_

Try out both those things and let me know how it goes for you.

**Comment by gilbertobitt** [comment]
@StanleyGoldman it work but now i not able to delete local repositories!

**Comment by StanleyGoldman** [comment]
@gilbertobitt Find me on gitter... https://gitter.im/github-for-unity/Unity
