### ISSUE TITLE
Improve support for macOS and Linux

### ISSUE THREAD

**Issue by StanleyGoldman** [github-for-unity/Unity#15]
**macOS & Linux**:
- [ ] Fix https://github.com/github-for-unity/sfw builds
- [ ] Package a portable git & git-lfs for internal use
- [x] #189 Provide the functionality to obtain a git shell

**macOS**:
- [ ] Add functionality to setup keychain helper

**Comment by thorade** [comment]
Sourcetree nicely supports switching between embedded/portable git and system git, maybe you could handle that in a similar fashion?

Would be nice to have some check for system git availability. 
On macOS, executing `git --version` in a terminal, will either print the version or trigger installation of the Xcode command line tools (about 120 MB, much smaller than full Xcode).

**Comment by StanleyGoldman** [comment]
Hi @thorade I was talking about this with some people.
We were wondering what are some of your motivations to want to be able to switch to a system git.

**Comment by shana** [comment]
@thorade We bundle git and lfs because we want to make sure you have the latest versions. xcode does not install lfs nor does it install the latest git, so on macOS homebrew is preferred, it's always up to date. You're free to change the git path in the settings tab to whatever you want, if you want to run your own system version.

Right now we're not bundling git on the mac (because of a bug in the unzipping code) so we do probe the system for existing git installations. 

To really trust the system git though we need version checks - letting an older git lfs overwrite hooks on a repo created with a more recent lfs can cause problems, same if we pick up a git without accompanying git lfs (that will definitely screw things up)

**Comment by thorade** [comment]
Sure, it was just a vague feeling that I would prefer to use the identical git with identical settings when working from Unity, the command line or from some git GUI. But I also see the benefits of bundling everything. And, as you said, I can change the path after installation.

**Comment by StanleyGoldman** [comment]
You raise a good point and yea @shana reminds me that you already have the ability to choose.
But we need to be able to verify that what you choose is okay to use. I opened #61.

**Comment by thorade** [comment]
There is now also #84

**Comment by StanleyGoldman** [comment]
#189 provides a working command line for mac
