### ISSUE TITLE
InvalidCastException (0.19, Unity 2017.1.1f1, Windows 10)

### ISSUE THREAD

**Issue by rdurnin** [github-for-unity/Unity#307]
### Prerequisites

InvalidCastException: Cannot cast from source type to destination type.
UnityEngine.UnitySynchronizationContext.ExecuteTasks () (at C:/buildslave/unity/build/Runtime/Export/UnitySynchronizationContext.cs:56)

### Description

This error message is repeated into the console x times per view refresh. It would seem that it corresponds somehow to the number of entries in the commit files view.

### Steps to Reproduce

1. Open a fresh project
2. Install the github package
3. Open the inspector and console views

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by StanleyGoldman** [comment]
Hey @rdurnin, sorry this fell below my radar.
Is this still a problem?

**Comment by Keisuki** [comment]
Hi, I'm having the same problem.  It started after my first push, and throws InvalidCastException several times per update.  I'm running the latest version of Github-for-unity on Unity version 2017.1.0f1.

**Comment by StanleyGoldman** [comment]
Hey @rdurnin @Keisuki 

Sorry this fell off my radar again, but I also need a bit more logs than what you guys are giving me.
Can you send a full copy of the log entry that is appearing?
Also, can you be specific about the version of GitHub for Unity you are using?

**Comment by Keisuki** [comment]
[Editor.log](https://github.com/github-for-unity/Unity/files/1553631/Editor.log)

Here is the log for a session I just started to demonstrate it.  I logged in, loaded my project.  Instantly 18 of the exception in question popped into the console.  I then pressed play, and 159 more appeared before I stopped the playback.  

In the log, there is also mention of Simulation.dll, which is a DLL I removed a long while ago, because it was causing unity to crash and I could not figure out how to uninstall the Microsoft Holographic Emulation package.  Even reinstalling Unity didn't work, so I just deleted the dll.

I don't know if that's really related to this, though.  Anyway, there's your log.

Let me know if you need anything else.

**Comment by StanleyGoldman** [comment]
Hey @Keisuki 

I tried to reproduce this a few times and I haven't been able to.
I even got a friend who works at Unity to look at the log file you posted. From what he sees he is not convinced the error you are seeing is coming from this plugin.
