### ISSUE TITLE
ApiClient should expose it's functionality as ActionTask or FuncTask types

### ISSUE THREAD

**Issue by StanleyGoldman** [github-for-unity/Unity#359]
Initially the idea was to avoid returning `Task` from `ApiClient`, but the patterns in that class have gotten muddy over time.

We want to expose all the functions from `ApiClient` as an `ActionTask` or `FuncTask`.
That way the tasks can be stacked in with our current task system.

**Comment by Nerzal** [comment]
Sounds like a job for me <3

**Comment by Nerzal** [comment]
So you want to use ActionTask or FuncTask as return type?
If you do so, you won't be able to use the async keyword, as ActionTask and FuncTask do not inherit from Task. 

When using async & await you have to use it all the way down or don't use it.
So do you wish to completely remove that async & await stuff and change the return type to ActionTask, or do you wish to change ActionTask & FunctionTask to let them inherit form Task so the async keyword is still available?

**Comment by shana** [comment]
@Nerzal Sorry, this issue got mislabeled - it’s a refactor we need to do to clean up pre-new-task-system code, not really a task suitable for someone new to the codebase. We can use async/await and Action/FuncTask together, we just need to make the APi that is exposed to Unity not use async/await, since Unity does not yet supoirt it out of the box.

**Comment by StanleyGoldman** [comment]
Hi @Nerzal, my bad, I probably shouldn't have put that label on the issue.

Thanks for wanting to participate though, hit me up on Gitter or Discord, maybe we can find something for you that would be interesting.
