### ISSUE TITLE
Infinite loading after installing (bug)

### ISSUE THREAD

**Issue by Allan-Nava** [github-for-unity/Unity#432]
Hello everyone,
I just started getting interested in unity. I download it today. After installation, unity ask me to sign in, what I have done. But after i have confirmed my mail address, unity seems to be in an infinity loop of loading. I can't do anything. I tried dowloading/installing it two more times but same result. I dont' know what to do. Have you some solutions?

![cattura](https://user-images.githubusercontent.com/22498435/32747504-318a3d46-c8b9-11e7-9ab6-e62d1f8b1b6b.PNG)

**Comment by StanleyGoldman** [comment]
Hi @Allan-Nava. Thanks for trying out our plugin but we don't yet support Unity 2017.2.

In order to clean this up:
1. Close any running instance of Unity
2. Navigate to the project folder where you installed the plugin
3. You should see a folder named `Assets\Plugins\GitHub\` and maybe a file named `Assets\Plugins\GitHub.meta`, delete them both.
4. Open your project and you should be fine from there.
