### ISSUE TITLE
Add labels or 2017.4 and 2018.1

### ISSUE THREAD

**Issue by tagsrock** [github-for-unity/Unity#647]
Love this effort!

It is unclear to me how to figure out what version of Unity have been tested. I only see that 5.3 has a issue. I go to labels, and see up to 2017.3, I assume of course because this is beta/alpha we are on our own to test. However with the announcement after GDC
https://blog.github.com/2018-03-23-GitHub-for-Unity-Beta/

Which I found by search engine via "Github for Unity 2018.1" support for that will be hot here soon. For now I suggest at least adding the labels so we can do it ourselves.

Soon (TM) I recommend a spot on the wiki, and on releases where it is made known what versions have been tested. For the wiki, we can document the various versions or if special steps where made, so maybe Wiki - Install Considerations
then - 5.3 list the work around
then - 2018.1 what works etc.

Just my thoughts.

**Comment by shana** [comment]
Good point, I've created labels for 2017.4, 2018.1 and 2018.2 (because it will come).

Unity 2017.4 is the LTS version and it's the exact same version as 2017.3, which is a main version that we test against. Being LTS, that means it will not get breaking changes.

The extension should also be running fine in Unity 2018.1, there are no massive breaking changes there that would give us problems (but labels are available if you find anything broken there!)
