### ISSUE TITLE
Settings - Save path on macOS does nothing

### ISSUE THREAD

**Issue by shana** [github-for-unity/Unity#656]
When there's no portable git on the system and it's just detecting whatever git is in the system, changing the git path in the settings view makes the view disabled but doesn't actually save anything.

**Comment by StanleyGoldman** [comment]
I did some debugging here as I ran into this as well.

The problem comes down to the validation that we perform before we save the user's change to disk.
When the user attempts to change the git path, we attempt to verify the version of git and git-lfs of the requested git path. We have a code path that accepts the change if the git and git-lfs meets the minimum requirement, we have a code path that rejects the change if git and/or git-lfs does not meet the minimum requirement, we **do not** have a code path that handles the scenario where the git or git-lfs version tasks fail catastrophically. Due to the issue in #650, that is what is currently happening.

**Comment by StanleyGoldman** [comment]
I sent in a PR for this.
