### ISSUE TITLE
No Periodic Polling for Locks

### ISSUE THREAD

**Issue by Joen-UnLogick** [github-for-unity/Unity#823]
### Description

Locks doesn't update automatically without user interaction. 
This is a clarification of bug #785 which fixed a part of the problem.

### Steps to Reproduce

1. Open the same unity project in from two locations at the same time
2. Navigate the project view to watch the same file in both instances of unity
3. Close all GitHub editor windows in both instances of unity
4. Lock a file in one of the projects
5. Observe that the second instance of Unity never marks the file as locked without opening the GitHub Editor Window

**Expected behavior:** 
I would expect that the other other project eventually polled the locked status and showed that the file was locked.

**Actual behavior:** 
Nothing, there is no visual cue that the file is locked. 

Locks are polled only on assembly reload (recompile, enter/leave playmode) and when you go into the locks tab of the github window. This works for most developers, but it doesn't always work for artists and level designers. 

**Reproduces how often:** 
100%

### Additional Information
We host our git server in house because our projects are quite large. This also means that we have plenty of bandwidth to let everyone poll once per second for all we care. The important thing is that everyone can see which files are locked and which ones are free for editing.

**Comment by shana** [comment]
Yeah, we added periodic polling, but I had to take it out at the last minute, because there's a problem with invoking lfs when you're not authenticated and "manager" is your default credential manager - if you don't login and dismiss the dialog, the lfs command locks up and Unity would not be able to do anything else until you kill the process tree. RC4 solves some of this, but I didn't want to ship constant polling until I make sure it's not going to randomly lock up Unity for people.

**Comment by Joen-UnLogick** [comment]
Right, well since they're artists and have no patience for git, we've set them up with ssh keys so they're auto authenticated. So why not hide this behind a checkbox with a warning? Our primary motivation for being early adopters on github for unity is making the artists and level designers happy... the developers are quite happy with their mix of various git clients.

**Comment by shana** [comment]
I understand that your specific use case may not be directly affected, but I have to think about everyone that's using GitHub for Unity, not just a specific subset. It's hard to determine whether the command is going to hang Unity due on lack of credentials, even if you're using ssh, so we need to add more checks and possibly add a checkbox UI in order to safely enable polling for everyone. Since we only hit the hanging problem at the last minute when doing the release, there was no time to safely let polling happen. It'll be reenabled next week when we push the next release out.

I've reopened the original bug, as it isn't fixed yet, closing this one as duplicate.
