### ISSUE TITLE
New Branch cannot push to origin

### ISSUE THREAD

**Issue by yuewah** [github-for-unity/Unity#839]
### Prerequisites

- Be sure to run with tracing enabled to capture runtime details in the log file
- Include the log file in the PR.
  - On Windows, the extension log file is at `%LOCALAPPDATA%\GitHubUnity\github-unity.log`
  - On macOS, the extension log file is at `~/Library/Logs/GitHubUnity/github-unity.log`

### Steps to Reproduce

1. setup using gitlab
2. new branch
3. commit some changes

**Expected behavior:** [What you expect to happen]
Push button enabled
**Actual behavior:** [What actually happens]
Push button dsiabled
**Reproduces how often:** [What percentage of the time does it reproduce?]
Always

### Additional Information
for existing branch, push is functional correctly

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by StanleyGoldman** [comment]
@IgnisIncendio I need logs and for you to go in more detail about what you did.

**Comment by ThomasAunvik** [comment]
Apparently i get the same issue, creating a new branch, no publish button.
My new branch isnt upstream, and `git push -u` does not work.
But `git push --set-upstream origin feature/steamworks`

Somehow GitLFS was uninstalled? I had to install it again. Do not think that was the reason.

Before git push: https://gist.github.com/ThomasAunvik/299c026f8b1bf274a873bb599ee1f794
After git push: https://gist.github.com/ThomasAunvik/5ea5502a8801486c17c42f2750341057

Twice Tested It.

**Comment by shana** [comment]
From what I can see of the code, there's one codepath that does `git push` instead of `git push -u [remote] [branch]`, and if the local branch isn't tracking a remote branch to start with, `git push` won't work. The point of the `git push` without setting upstream is that you could have a local branch configured to push to some other branch that's not the default we would set, and I don't want to trample all over some configuration you may already have, but it looks like this codepath is being called when it shouldn't. Definitely a bug!

**Comment by StanleyGoldman** [comment]
Incoming fix. We hope to push this out next week.
