### ISSUE TITLE
Add `diff` attribute to .gitattributes for text assets

### ISSUE THREAD

**Issue by shana** [github-for-unity/Unity#847]
We should add a `diff` attribute to `.gitattributes` on the filetypes that are text files (like prefab, asset, unity, etc), so that diffs for them are shown on the command line (currently git skips showing diff because it thinks these files are binary)

**Comment by FurkanKambay** [comment]
@shana Since the files are text files, why do we avoid EOL conversions exactly? I'm personally considering removing `-text` and adding `eol=lf` for my repo. Is there something I'm missing?

Also, Unity has other file types like .mat for materials; did those get overlooked or do they not need the merge tool for some reason? I can open PR for that after I find out all the file extensions.

**Comment by shana** [comment]
@FurkanKambay These are files generated and managed by Unity, and Unity always generates them with a certain EOL, which means the eol conversion will always spam the user with "Warning LF will be replaced" etc etc if they commit on the command line. I don't see the point of letting git do eol conversions on these files by default, especially on windows.

As for .mat files, they got overlooked :/ I honestly think I've overlooked other yaml types - probably animations too?

**Comment by FurkanKambay** [comment]
@shana I see what you mean. I guess that warning didn't occur to me cause I have `core.autocrlf=false`. So I'm just gonna do that locally. Thanks for explaining.

I created an empty project and created almost everything under Assets/Create. Here it is: https://i.imgur.com/QODfnOr.png

I'm gonna open a PR. We can adjust there.

**Comment by shana** [comment]
Yeah, `core.autocrlf=false` avoids them, but git has `true` as the default so I must have it as default as well so I suffer like our users suffer and it's so.annoying.urgh.
