### ISSUE TITLE
"No Remote Configured"

### ISSUE THREAD

**Issue by EmmetOT** [github-for-unity/Unity#895]
I feel like I'm missing something because I can't figure out how to finish my setup. I'm logged in, and I've created a repository. I have the URL in the form _https://github.com/EmmetOT/repoName.git_

It seems like the next step would be to put this URL into the field under 'Repository Configuration' and click 'Save Repository'? But when I do this, nothing happens and the header still reads 'No remote configured.' I can't see an other applicable options.

**Comment by StanleyGoldman** [comment]
Hey @EmmetOT. Normally the way to go about it is to create the project and repository locally. Then use the publish button to automatically create the repository on GitHub.com and have your stuff pushed to it.

If I am correct, it sounds like you did both, created a repository locally and created a repository on GitHub.com. Which is also fine and your assumption about what to do with the url is also correct. It should automatically update after you put the value in and hit save like this.

![2018-08-27_09-48-38](https://user-images.githubusercontent.com/417571/44663418-812f6180-a9de-11e8-88a5-8baa5c11f33c.gif)

Since it sounds like that is not happening, can you "Enable Trace Logging" and send us the log file, we can try to figure it out from there.

**Comment by shafy** [comment]
I have the same issue

**Comment by StanleyGoldman** [comment]
@shafy looking at your log, this message is the problem i fixed in #921

**Comment by StanleyGoldman** [comment]
Hey @EmmetOT since I haven't heard from you here, I'm going to close this issue.

If you are still having this problem, can you "Enable Trace Logging" and send us the log file, we can open this issue back up and try to resolve it.
