### ISSUE TITLE
Can't commit files locally, git-lfs error

### ISSUE THREAD

**Issue by IgnisIncendio** [github-for-unity/Unity#901]
[github-unity.log](https://github.com/github-for-unity/Unity/files/2335105/github-unity.log)

### Description

Github for Unity doesn't commit files, it just says "Staging files" and ends.

### Steps to Reproduce

1. Initialize new git on new Unity project
2. Have a variety of asset files like code and mp3 files
3. In Changes, click All, type "Initial Commit 2" and click on Commit

**Expected behavior:** Github for Unity commits files locally.

**Actual behavior:** Github for Unity shows "Staging Files..." for 1 second, then stops committing with no errors in the GUI. There's errors in the log though.

**Reproduces how often:** Every time

### Additional Information

Probably something related to git-lfs, so non-code files like mp3 
is necessary.

**Comment by StanleyGoldman** [comment]
Hey @IgnisIncendio Thanks for testing out our stuff and reporting this issue.

Sorry it took so long to get back to you, I'm working on a few other projects at the same time.

**Comment by StanleyGoldman** [comment]
Would you be able to enable trace logging and reproduce the issue?
The log file should give me a better clue as to what is going wrong for you..

**Comment by StanleyGoldman** [comment]
Hey @IgnisIncendio I'd like to find out more about your issue.
I'm going to close this for now.

But if you can, please test with the latest version of GitHub for Unity and let me know if you can reproduce this.

I'd be happy to help you figure it out.

**Comment by IgnisIncendio** [comment]
Sorry for not replying to this issue in a long time! I kind of forgot it existed and I don't check Github often. I just tried the latest version (1.0.3) on Unity 2018.2, but I was unable to test it as no changes showed up in the Changes tab. I saw #898, and tried the build from there, but it wouldn't work as well.

**Comment by IgnisIncendio** [comment]
Done!

**Comment by StanleyGoldman** [comment]
Okay, i'm going to close this for now

**Comment by vsadnikcorp** [comment]
I have the exact problem described above, except I have sprites instead of MP3 files--should I start a new issue or will this one re "re-activated"?
********************
Description
Github for Unity doesn't commit files, it just says "Staging files" and ends.

Steps to Reproduce
Initialize new git on new Unity project
Have a variety of asset files like code and sprites
In Changes, click All, type "Initial Commit 2" and click on Commit
Expected behavior: Github for Unity commits files locally.

Actual behavior: Github for Unity shows "Staging Files..." for 1 second, then stops committing with no errors in the GUI. 
Reproduces how often: Every time
