### ISSUE TITLE
How can I remove my unity project from a local repository.

### ISSUE THREAD

**Issue by cyberangel67** [github-for-unity/Unity#912]
I deleted the .git folder and .git ignore and looked everywhere I thought this information could be stored, but couldn't find anything.

Now when I open up my Unity project, it will not initialise saying I need to enter my name and email. When I do enter my name and email and save it, its not persisting and is empty when I go back to the settings tab.

And I can no longer sign in.

So now I want to go back to scratch, like my project was never committed and/or setup and start from scratch. And no, there is no remote sync copy, because I can't sign in.

**Comment by StanleyGoldman** [comment]
In order to remove git and GitHub for Unity from your project.
I would delete the following:
- `./.git*`
- `./Assets/Plugins/GitHub*`

I do not know what sign in you are referring to.

**Comment by cyberangel67** [comment]
In the settings it asks for a name and email, when I hit save that disappears.

And after about 20 times deleting these files I managed to get it all working again, just something remained that didn't allow me to save that information in the settings.

I had also noticed that the git location, where it asked for package or system, would not save sometimes as well.

So I have no idea what I did, but after the 20th delete I managed to get it all working. The only issue I have now, is that Unity Github, seems to not want to update. I know there is a newer version that 1.0.0, but nothing I can do or find helps. Which is what got me into this mess in the first place.

**Comment by shana** [comment]
@cyberangel67 If you're unsure which version of GitHub for Unity you have, you can manually install the latest version by doing the following:

- Download the latest release from our [releases page](https://github.com/github-for-unity/Unity/releases). You want the file with the extension `.unitypackage`
- Open your project in Unity
- Double click the file you've download from the releases page. This will open a popup in Unity.
- Click `Import` on the popup in Unity

The latest version is now installed. In the Unity console tab, there will be a message noting what version of GitHub for Unity is running, but it might not show up immediately, since it only shows up the first time you run Unity (otherwise it would be annoying). If you're unsure, restart Unity to see the message.

**Comment by shana** [comment]
As for the username and email not being saved, what this does is tell git to record this information. Feels like something went wrong in this step, but there's no way to tell without looking at the logs. When you open an issue, there's a prerequisite section with information on what we need in order to track down problems, specifically in relation to log files. Without this information, we can only guess at what's going on. Please make sure you read the issue instructions when you open issues and upload the logs that we need:

- Be sure to run with tracing enabled to capture runtime details in the log file
- Include the log file in the issue.
  - On Windows, the extension log file is at `%LOCALAPPDATA%\GitHubUnity\github-unity.log`
  - On macOS, the extension log file is at `~/Library/Logs/GitHubUnity/github-unity.log`


Regarding username and email, you can double check that this information is correctly saved by doing the following

- Open a git command line. You can do this from Unity by going to the `Window` top level menu and selecting `GitHub Command Line`, which will open a command line for running git commands
- Run `git config --global user.name`. It should output your name (usually first and last name)
  - If it doesn't or it's incorrect, set your name with `git config --global --replace-all user.name Your Name`
- Run `git config --global user.email`. It should output your email
  - If it doesn't or it's incorrect, set your email with `git config --global --replace-all user.email your@email.com`

The name and email are saved in the git configuration file. The global configuration file is a text file in `%USERPROFILE\.gitconfig` (on Windows) / `~/.gitconfig` (on mac). You can open it with a text editor and see what values it has (your name and email should be in there).

**Comment by shana** [comment]
> Cheers, the front page only has release 1.0.0 and the Unity Asset store only as 1.0.0rc4 I think it is.

Ugh, yes, unity.github.com is out of date, thank you for pointing that out. I've fixed it now.
The asset store requires a manual update, so we don't send every version up to it (since you'd be immediately notified of an update if you install it that way). The latest version is going to go up, since it has important updates to the 2018 compatibility, but it takes two weeks for the asset store to have it.

> Well my real question, is why Unity no longer detects a new version, I think I select skip this version

Yeah, that might have been it. Skip will only skip a specific version, so you'll get notified of future updates after this one.

**Comment by cyberangel67** [comment]
Ok so I download 1.0.3 and I get an access denied on a DLL, so how am I suppose to upgrade it

**Comment by cyberangel67** [comment]
> > Cheers, the front page only has release 1.0.0 and the Unity Asset store only as 1.0.0rc4 I think it is.
> 
> Ugh, yes, unity.github.com is out of date, thank you for pointing that out. I've fixed it now.
> The asset store requires a manual update, so we don't send every version up to it (since you'd be immediately notified of an update if you install it that way). The latest version is going to go up, since it has important updates to the 2018 compatibility, but it takes two weeks for the asset store to have it.
> 
> > Well my real question, is why Unity no longer detects a new version, I think I select skip this version
> 
> Yeah, that might have been it. Skip will only skip a specific version, so you'll get notified of future updates after this one.

cool, well I wish there was a way to revert that, I have accidentally done that with Unity and no patches in that version are ever notified to me.

**Comment by shana** [comment]
> And I swear Unity was detecting a 1.0.4 release so why is there so many version in so many places. I mean most people are going to get it from Unity Asset store and that is an older RC not even the 1.0.0 release on the main UnityGithib page.

There isn't a 1.0.4 yet, so not sure how you saw that.

> Ok so I download 1.0.3 and I get an access denied on a DLL, so how am I suppose to upgrade it

Unity locks that DLL sometimes, but that's ok, it doesn't need to be updated. If the import failed because of it, you can try importing again, but this time make sure to deselect the `x64` and `x86` folders in the `Import` popup, as shown in this image:

![image](https://user-images.githubusercontent.com/310137/45705472-fc1d0f80-bb79-11e8-8149-a0fb15348dac.png)

> cool, well I wish there was a way to revert that, I have accidentally done that with Unity and no patches in that version are ever notified to me.

Our update popup will only skip that specific version that is being offered to you. If you skipped 1.0.3 (as it seems you did), that's the only version that will be skipped. We don't have a GUI to change this setting, but you can do the following to see if you've skipped it:

- Open the file `%LOCALAPPDATA%\GitHubUnity\usersettings.json` in an editor
- If you have skipped a version, there will be an entry with `"SkipVersion":{"Version":"1.0.3"}`
- If there is, change it to something like `"SkipVersion":{"Version":"0.0.3"}`. This will be enough to "unskip" the version.

**Comment by cyberangel67** [comment]
Yeah I got it installed, just ran the package a second time. Seems that if the Github window is open it fails on that dll.

And thanks, that was exactly what I was hoping to find, I swear I even looked in there and didn't see it.

Oh wait, is there another place that might be installed, because I deleted that directly fully. anywhere I found GitHubUnity I deleted the entire folder.

**Comment by shana** [comment]
> Oh wait, is there another place that might be installed, because I deleted that directly fully. anywhere I found GitHubUnity I deleted the entire folder.

If you mean the `usersettings.json` file, that's the only place where that setting is.
The other file with configuration settings is `C:\ProgramData\GitHubUnity\systemsettings.json`. This has the information about what versions of git and git lfs are installed on your system and where.

**Comment by cyberangel67** [comment]
Is it possible Unity caches this some how?

Because I know for a fact I deleted both those folders before opening Unity and importing the package from the Asset Store and I never got challenged for the update after skip this version.

**Comment by shana** [comment]
@cyberangel67 It checks for updates once a day, but the timestamp for the update check is kept in those files, so if you deleted them it should have notified you. I can't know what's failing without looking at the logs (which are also on those folders). If you run into problems again, make sure you copy the logs so they don't get overwritten and send them in so we can see what's going on. Turn on trace logging too so it has more information.

**Comment by cyberangel67** [comment]
hmm, could be as I did this all within an hour.

Cheers.
