### ISSUE TITLE
"Assets/MixedRealityToolkit/_Core/Utilities/AsyncUtility/AwaiterExtensions.cs(158,50): error CS0433: The imported type `System.Runtime.CompilerServices.INotifyCompletion' is defined multiple times"

### ISSUE THREAD

**Issue by Ecnassianer** [github-for-unity/Unity#951]
### Description

I'm trying to use GitHub for Unity with the Mixed Reality Toolkit and I get this error when I bring in GitHub for Unity:
Assets/MixedRealityToolkit/_Core/Utilities/AsyncUtility/AwaiterExtensions.cs(158,50): error CS0433: The imported type `System.Runtime.CompilerServices.INotifyCompletion' is defined multiple times

As well as this error:
Assets/MixedRealityToolkit/_Core/Utilities/AsyncUtility/AwaitYieldInstructions/WaitForBackgroundThread.cs(30,16): error CS0433: The imported type `System.Runtime.CompilerServices.ConfiguredTaskAwaitable' is defined multiple times

I got similar errors for Tasks and I was able to unload Github For Unity's System.Threading dll and they went away. What DLL can I unload to get the INotifyCompletion redefinition to go away??

### Steps to Reproduce

1. Import [Mixed Reality Toolkit](https://github.com/Microsoft/MixedRealityToolkit-Unity/releases/tag/2018.9.0-Beta) (the vNext beta version)
2. Import Github For Unity.
3. Explode

**Expected behavior:**
It compiles.

**Actual behavior:**

Error messages.

**Reproduces how often:**

100%

### Additional Information

**Comment by Ecnassianer** [comment]
So I eventually figured out that I could disable AsyncBridge.Net35 to get it to compile. I get an "Initializing Github For Unity 1.1.1" and it immediately recompiles with the DLLs enabled and breaks itself. It's like a dll prank! XD

**Comment by Ecnassianer** [comment]
I also tried deleting those two dlls, but then everything explodes even worse. Unity wants to import the DLLs and fails to find them and I get nowhere.

**Comment by StanleyGoldman** [comment]
Hey @Ecnassianer thanks for trying our stuff out. It seems we have an assembly colliding with that package. I will test it out myself and let you know what I figure out.

**Comment by Ecnassianer** [comment]
Thank you!

**Comment by shana** [comment]
Hi @Ecnassianer. So sorry for the delay in looking into this, we've been really swamped recently.

I've tested the mixed reality toolkit locally, and I suspect that your problem is that the project you were trying to import the toolkit and github for unity into was not set to the 4.6 runtime. The 3.5 versions of the DLLs for threading are only loaded if the runtime is set to 2.0 in Unity, which is the default on new projects (which you can change in Project Settings -> Player in Unity. When the runtime is set to 4.6, none of the threading libraries get loaded, which is the desired behavior in this case. The mixed reality toolkit requires the 4.6 runtime, so as long as you have the project set to this runtime before you import GitHub for Unity, you should not get any conflicts.

I'm closing this one out, let us know if things are still failing for you.

**Comment by Ecnassianer** [comment]
Weird, I wonder how I got into that state, since my MRTK project worked before I added GitHub For Unity. Strange.

In any case, I can't repro it anymore, and Github for Unity is working in my project. Thanks for looking into this!
