### ISSUE TITLE
How to view merge conflicts?

### ISSUE THREAD

**Issue by amandelman** [github-for-unity/Unity#981]
I've read through the documentation and checked both open and closed issues, but can't seem to find info on viewing and resolving merge conflicts. Apologies if it this is in fact already posted somewhere, but, can someone tell me what the workflow is for viewing and resolving merge conflicts? 

I've managed to set up a working repo and make some commits, but I'm hesitant to let my teammates loose on the project until I know we can deal with merge conflicts. 

For the record, we're all new to Unity and new-ish to GitHub...

Thanks for any help you can offer.

**Comment by StanleyGoldman** [comment]
Hey @amandelman. Thanks for checking our stuff out. This is a bit of a long story but it has a good ending.

We _initially_ thought we were setup correctly to integrate merging, but I can't say that even we fully knew what that meant. We attempted to follow the instructions [here](https://docs.unity3d.com/Manual/SmartMerge.html), but a very astute user pointed out some mistakes in #943 and asked some questions that made us do some research.

It turns out the documentation to integrate git from Unity was incorrect, (we are submitting a bug report to them so they can fix it). We figured out the correct integration and fixed it in #974 & #978. We are going to release the fix soon (this week or next).

I can tell you how it **should** work in the next release. Unity provides a tool called **Smart Merge** a.k.a. **UnityYamlMerge**. Unity's serialization process is non-deterministic and Unity provides this tool to perform a semantic merge for you. After this next release, when you perform a merge, this tool will get invoked automatically by git. When the tool is not able to perform the merge, it will invoke whatever diff tool Unity finds on your system to allow you to finish the merge. You can choose what fallback tool is used in your Unity settings.

![image](https://user-images.githubusercontent.com/417571/49872062-ea987c00-fde5-11e8-9f2f-14e19de2693b.png)

I hope the explanation helps.
Feel free to re-open this issue if you have any additional questions.
