### ISSUE TITLE
Reported issue with v1.2.0 and Unity 5.6.4

### ISSUE THREAD

**Issue by RamiroOliva** [github-for-unity/Unity#986]
Please pull this update, it completely breaks any existing project.
Just imported the new package onto existing (and functional) Github plugin 1.1.0 in Unity 5.6.4.
After import finishes, lot of GUI error occurs. Restarted Unity and same problem.
Recreated Github window (closing and opening using the Window menu). Same. Plugin is broken.
Try it yourself please.

**Comment by StanleyGoldman** [comment]
Can you post a log?

**Comment by shana** [comment]
I just installed Unity 5.6.4, created a new project, installed GHU 1.1.0, initialized a repository, committed some files and published the repository (https://github.com/shana/unity-test-564), then updated to GHU 1.2.0 and committed and pushed with it without a problem.

I noticed that the GitHub window doesn't show up docked when the plugin is updated, I presume because all the DLLs are disabled up front before we enable the ones for the correct .net profile and the docking somehow gets confused (not sure about this), but otherwise everything seems to be working fine.

@RamiroOliva Could you upload the unity editor log and the plugin log so we can see the errors, please?

**Comment by RamiroOliva** [comment]
Ok, tried again. This time I removed existing plugin (1.1) before importing 1.2 and no GUI errors occur, but... keep reading:

Background:
- Unity project in Unity 5.6.4
- Github for Unity 1.1.0 in Plugins folder (default installation path, nothing changed)

Step 1: Download Github for Unity 1.2.0
Step 2: Removed existing plugin 1.1
Step 3: Import version 1.2

In the changes tab, it shows the following:
https://i.imgur.com/xqdCmyz.png

It seems the Github folder no longer is ignored by the plugin.
If I discard those changes then it reverts to 1.1.
Should I commit them then?

**Comment by shana** [comment]
Yes, those changes are expected. You already have the previous version committed to your repository, so you should commit these changes in order to ensure you save the latest version in your repository.

**Comment by RamiroOliva** [comment]
Sorry for the naive question: shouldn’t Github plugin add itself to the ignore list? I don’t want it to be included in the repo.

**Comment by StanleyGoldman** [comment]
Hi @RamiroOliva sorry no one ever got back to you on this.
It is normal for Unity plugins to be committed to source control. GitHub for Unity included.

It sounds like all your other issues were resolved.
If you have another question, feel free to re-open the issue.
